---
- hosts: all
  become: true
  tasks:
    - name: Install apace2 and support packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
