---
- hosts: all
  become: true
  tasks:

    - name: remove apache2 and support package
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
        update_cache: yes
